#+HTML_HEAD: <style>img{max-width:100%}.figure-number{display:none}</style>

#+TITLE: SAN: PCB Design

* Objectives

- Find dimensions of PCBs that can then be used with KiCad.

- Check the schematic designed with KiCad.

- Create a manufacturing ready board layout.

- Optimize price and manufacturing time.


* 3D mockup

#+BEGIN_EXPORT html
<iframe allowfullscreen id="irisModel" width="100%" height="600px"
src="mockup.iris/index.html" frameBorder="0"></iframe>
#+END_EXPORT

Via the top left menu, layers can be turned off to reveal the inside
of the sphere.  Only certain large components are part of the mockup.
The 3D mockup has been created with the [[https://mcneel.github.io/Iris/][Iris plugin]] from the Rhino 3D
model file [[./mockup.3dm][mockup.3dm]].

- The diameter of the sphere is 50 mm.

- Only larger components have been included.

- There are two PCBs in order to get the LEDs in the correct
  positions.

- The right angle SMD LEDs shine light sidewards.  They are mounted at
  an offset from the shell in order to diffuse light.

- The top USB connector is abused for interfacing with an FTDI.  This
  is to easily be able to update the firmware.


* Schematic

#+BEGIN_EXPORT html
<img alt="Main circuit" src="./images/node.svg">
#+END_EXPORT

#+BEGIN_EXPORT html
<img alt="NeoPixel circuit" src="./images/neopixel-NeoPixel 1.svg">
#+END_EXPORT

This is a snapshot of the schematic.  Only one of the NeoPixel
circuits is shown.  They are all the same except for the component
references.

The most recent version of the schematic can be found in the KiCad
project [[https://github.com/feklee/san/tree/master/nodes/pcb/node][node]] in the SAN repo on GitHub.


* Open questions

- /Is there a better way to connect the PCBs?/

  An eight wire FCC is used.  Nicer would be a solution without FCC,
  where the boards can simply be plugged together, and done.

  See also the thread [[https://www.mikrocontroller.net/topic/466727][Platinen über Kreuz kontaktieren]] (German) in the
  forum on Microcontroller.net.

- /Use plated-trough holes as cheap and simple alternative to the
  Molex 0533980271 [[https://www.molex.com/product/picoblade.html][PicoBlade]] connectors?/

  The PicoBlade connectors are for connecting the BNC connectors.
  Without plated-trough holes, the cables would be manually soldered
  to the PCBs, for example by participants during a workshop.

- /Should there be a diode in front of the 5 V regulator?/

  For comparison: The Arduino Uno has an M7 diode right after =PWRIN=.
  The Arduino Pro Mini doesn’t have a diode to protect agains reverse
  polarity.  Still – from experience – reversing polarity doesn’t
  damage the board.

- /Which board manufacturer?/

  Examples are [[https://jlcpcb.com/][JLCPCB]], PCBWay, or Seeed.  Seeed has a list of
  components that they have in stock, which speeds up sourcing.  Felix
  also has a contact at Seeed, met in person in Berlin. In 2017, with
  the [[https://flic.kr/p/21c8Cqx][HTTC7 group]] he visited the Seeed [[https://www.flickr.com/photos/maltman23/38194661961/in/album-72157665929390189/][assembly line]] in 2017 in
  Shenzhen.

- /Which RGB LEDs should be used?/

  The Kingbright APFA3010SEEZGKQBKC rectangular SMD LED looks good.
  An alternative is the APFA3010LSEEZGKQBKC, which is considerably
  less bright by default.

- /Add holes for regular through hole NeoPixel LEDs?/

  This is for the case the WS2811-SMD-LED circuits turn out not to
  work.  There won’t be enough time to do a second production run.

  Solder bridges could be used to have the easy option to disconnect
  nonfunctional SMD NeoPixel circuits.

- /Add a solder bridge to easily turn off the accelerometer circuit?/

  Then the circuit can be easily disconnected in case it doesn’t work.

- /Can a pick and place machine put LEDs protruding the edge of the
  PCB?/

  Having LEDs protrude the edge avoids having light blocked by the
  PCB.

- /Do the selected LEDs have a circular uniform viewing angle?/

- /Is it OK to abuse a Micro-USB port for programming the FTDI?/

  This is the port accessible through the top shell.  As long as GND
  and +5 V are in the same position as with USB, things could be safe.

  Micro-USB ports have the required five pins.  They are readily
  available, cheap, and small.

- /Use QFN package for ATmega328P?/

  …instead of TQFP

- /Can the assembly house or the parts vendor burn an Arduino boot
  loader on the ATmega328P?/

  Otherwise, the second Micro-USB port can be used to burn the boot
  loader.  Six pins are required, but power could be taken from the
  other Micro-USB port.

  Digi-Key offers the option, but the assembly house may source from
  another vendor.

- /Should the top PCB get more space?/

  It could be extended downwards at the expense of the bottom PCB.

- /Move the accelerometer circuit to the top PCB?/

  That way the FCC would require only six instead of eight wires.
  However, there may not be enough space for the circuit in the top
  PCB.


* Source of 3D compontents

- BK-912: [[http://www.memoryprotectiondevices.com/3d/download.php?pn=BK-912][BK-912.STEP]]

- APFA3010LSEEZGKQBKC: [[http://www.kingbrightusa.com/images/catalog/3D/STEP/APFA3010.STEP][APFA3010.STEP]]

- Molex PicoBlade 0533980271: [[https://www.molex.com/pdm_docs/stp/53398-0271_stp.zip][533980271.stp]]

- TE AMP Mini CT 292228-2: [[https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+View+Model%7F292228-2%7FA%7F3d_stp.zip%7FEnglish%7FENG_CVM_292228-2_A.3d_stp.zip%7F292228-2][c-0292228-02-a-3d.stp]]

- Amphenol 10118193-0001LF: [[https://cdn.amphenol-icc.com/media/wysiwyg/files/3d/s10118193.zip][10118193-0001lfc.stp]]

- Amphenol SFW8R-2STE1LF: [[https://cdn.amphenol-icc.com/media/wysiwyg/files/3d/ssfw08r_2_4stlf.zip][ssfw08r_2_4st_lf.stp]]

- ATMega 328P-AU: [[https://digikey.ultralibrarian.com][32A.step]] (Ultra Librarian for Digi-Key)

- BNC connectors: Amphenol
